services:
  - type: web
    name: california-house-pricing
    env: docker
    dockerfilePath: ./Dockerfile
    branch: main
    plan: free
    region: oregon
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        value: "rnd_TQkVYv1Hoh648X79837Ms0DGv8ZA"
